version: '3'

services:

  # Proxy for ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
      - ./data/ssl/dhparams.pem:/etc/nginx/dhparam/dhparam.pem
    environment:
      DHPARAM_GENERATION: "false"
    depends_on:
      - nextcloud
    networks:
      default:
        aliases:
          - ${NEXTCLOUD_DOMAIN}
          - ${COLLABORA_DOMAIN}
          - onlyoffice.local.dev.bitgrid.net
          - collabora2.local.dev.bitgrid.net
          - nextcloud2.local.dev.bitgrid.net
          - nextcloud3.local.dev.bitgrid.net

  nextcloud:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      # SQL: 'sqlite'
      # SQL: 'mysql'
      SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "${NEXTCLOUD_DOMAIN:-nextcloud.local}"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      #- database-mysql
      - database-postgres
      - redis
      - mail

  nextcloud2:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: nextcloud2.local.dev.bitgrid.net
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data2:/var/www/html/data
      - config2:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}1:80"
    depends_on:
      - redis
      - mail

  nextcloud3:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      SQL: 'sqlite'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: nextcloud3.local.dev.bitgrid.net
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data3:/var/www/html/data
      - config3:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}3:80"
    depends_on:
      - redis
      - mail

  database-mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    ports:
      - "${PORTBASE:-800}2:80"

  database-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  redis:
    image: redis:3

  ldap:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    expose:
      - 389
      - 636
    ports:
      - 3389:389
    volumes:
      - ./data/example.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  ldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "${PORTBASE:-800}8:80"

  saml:
    image: unicon/simplesamlphp
    volumes:
      - ./docker/configs/var-simplesamlphp/config:/var/simplesamlphp/config
      - ./docker/configs/var-simplesamlphp/cert:/var/simplesamlphp/cert
      - ./docker/configs/var-simplesamlphp/metadata:/var/simplesamlphp/metadata
    environment:
      VIRTUAL_HOST: "sso.local.dev.bitgrid.net"
    expose:
      - 80

  mail:
    image: mailhog/mailhog
    expose:
      - 80
    environment:
      VIRTUAL_HOST: "mail.local.dev.bitgrid.net"
      VIRTUAL_PORT: 8025


  smb:
    image: dperson/samba
    ports: 
      - 139
      - 445
    environment:
      # -u "<username;password>[;ID;group;GID]"
      USER: "admin;admin"
      USER2: "user1;user1"
      USER3: "user1;user1"
      # -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
      SHARE: "public;/smbmount;yes;no;yes"
      SHARE2: "user1 private share;/smb/user1;no;no;no;user1"
      SHARE3: "user2 private share;/smb/user2;no;no;no;user2"
    volumes:
      - smb:/smbmount

  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

  collabora:
    image: collabora/code:latest
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      domain: ${NEXTCLOUD_DOMAIN}
      username: admin
      password: admin
      VIRTUAL_HOST: ${COLLABORA_DOMAIN}
      VIRTUAL_PORT: 9980
      VIRTUAL_PROTO: https
  
  collabora2:
    image: collabora/code
    restart: on-failure
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      domain: nextcloud2.local.dev.bitgrid.net
      username: admin
      password: admin
      VIRTUAL_HOST: collabora2.local.dev.bitgrid.net
      VIRTUAL_PORT: 9980
      VIRTUAL_PROTO: https

  onlyoffice:
    image: onlyoffice/documentserver:latest
    environment:
      VIRTUAL_HOST: onlyoffice.local.dev.bitgrid.net
    expose:
      - '80'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: nextcloud
      MINIO_SECRET_KEY: nextcloud
    ports:
      - "${PORTBASE:-800}5:9000"
    volumes:
      - objectstorage_minio:/data
    command: server /data

  s3:
    image: lphoward/fake-s3
    expose:
      - 4569
    volumes:
      - objectstorage_fakes3:/fakes3_root

  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile.elasticsearch
    environment: 
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  data:
  data2:
  data3:
  config:
  config2:
  config3:
  document_data:
  document_log:
  objectstorage_fakes3:
  objectstorage_minio:
  smb:
  elasticsearch_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
