name: 'Docker Publish'

on:
  push:
    branches:
      - master


jobs:
  push_to_registry:
    name: Build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - php80
          - php74
          - php73
          - php72
          # - php71
          - saml
          - nginx
          - elasticsearch
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker/
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile.${{ matrix.container }}
          tags: |
            ghcr.io/juliushaertl/nextcloud-dev-${{ matrix.container }}


